### ISSUE TITLE
Fatal runtime error: Rust panic on nightly neovim

### ISSUE THREAD

**Issue by astridlyre** [shaunsingh/oxocarbon.nvim#9]
Hey! Great colorscheme.

For some reason, a few days ago it started crashing nightly neovim for me. I'm using the AppImage version.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("\'ctermbg\' must be string or integer")', /home/ml/.cargo/git/checkouts/nvim-oxi-68d2fdc1d1cdbe82/15fb30d/nvim-oxi/src/lua/lua.rs:41:12
           note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
                                                                                        fatal runtime error: Rust panics must be rethrown
                               Aborted (core dumped)
```

It crashes with the above message. With `RUST_BACKTRACE=1`, we get more verbosity.

```
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: NvimError("\'ctermbg\' must be string or integer")', /home/ml/.cargo/git/checkouts/nvim-oxi-68d2fdc1d1cdbe82/15fb30d/nvim-oxi/src/lua/lua.rs:41:12
stack backtrace:
   0: rust_begin_unwind
             at /rustc/1.63.0/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/1.63.0/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/1.63.0/library/core/src/result.rs:1805:5
   3: luaopen_oxocarbon
[?25l(B[m[H[2J[?1004h[?12h[?25h   4: lj_BC_FUNCC
   5: lj_cf_package_require
             at /home/runner/work/neovim/neovim/.deps/build/src/luajit/src/lib_package.c:464:3
   6: lj_BC_FUNCC
   7: lua_pcall
             at /home/runner/work/neovim/neovim/.deps/build/src/luajit/src/lj_api.c:1145:12
   8: nlua_pcall
             at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:135:16
   9: nlua_exec_file
             at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:1631:7
  10: do_source
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:1991:5
  11: source_callback
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:197:9
  12: do_in_cached_path
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:404:14
  13: do_in_runtimepath
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:749:16
  14: source_runtime
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:767:10
  15: load_colors
             at /home/runner/work/neovim/neovim/src/nvim/highlight_group.c:582:14
  16: ex_colorscheme
             at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:5160:14
  17: execute_cmd0
             at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:1569:29
  18: do_one_cmd
             at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:2218:7
  19: do_cmdline
             at /home/runner/work/neovim/neovim/src/nvim/ex_docmd.c:571:20
  20: source_using_linegetter
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:1774:16
  21: do_source_str
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:1825:10
  22: nvim_exec
             at /home/runner/work/neovim/neovim/src/nvim/api/vimscript.c:67:3
  23: nlua_api_nvim_exec
             at /home/runner/work/neovim/neovim/build/src/nvim/auto/lua_api_c_bindings.generated.c:5473:22
  24: lj_BC_FUNCC
  25: lj_cf_package_require
             at /home/runner/work/neovim/neovim/.deps/build/src/luajit/src/lib_package.c:464:3
  26: lj_BC_FUNCC
  27: lua_pcall
             at /home/runner/work/neovim/neovim/.deps/build/src/luajit/src/lj_api.c:1145:12
  28: nlua_pcall
             at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:135:16
  29: nlua_exec_file
             at /home/runner/work/neovim/neovim/src/nvim/lua/executor.c:1631:7
  30: do_source
             at /home/runner/work/neovim/neovim/src/nvim/runtime.c:1991:5
  31: do_user_initialization
             at /home/runner/work/neovim/neovim/src/nvim/main.c:1943:10
  32: source_startup_scripts
             at /home/runner/work/neovim/neovim/src/nvim/main.c:2020:9
  33: main
             at /home/runner/work/neovim/neovim/src/nvim/main.c:396:3
  34: <unknown>
  35: __libc_start_main
  36: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: Rust panics must be rethrown
```

**Comment by gaetgu** [comment]
FWIW I am also receiving the same error, macOS 13, nvim 0.8.0-dev

**Comment by noib3** [comment]
hey `nvim-oxi` maintainer here. This should have been fixed on the latest master. Could you try cloning the project, doing a `cargo update` to update `oxocarbon.nvim`'s version of `nvim-oxi` and see if the issue persists?

**Comment by luxus** [comment]
@noib3 thanks.
@shaunsingh i created a PR
